
services:
  db:
    container_name: my_postgres_prod
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  db_cache:
    container_name: my_redis_prod
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data

  server:

    image: woundex/taetir-server:latest
    container_name: my_backend_prod
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://db_cache:6379
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - db
      - db_cache
    command: npm start

  client:
    image: woundex/taetir-client:latest
    container_name: my_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db_data_prod:
  redis_data_prod:
