version: "3.9"
services: 
  db:
    container_name: my_postgres
    image: postgres:16  # Or your preferred PostgreSQL version
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: