
version: '3.8'

services:
  db:
    container_name: my_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  db_cache:
    container_name: my_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: my_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules 
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - REDIS_URL=redis://db_cache:6379
      - PORT=5000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
      - db_cache
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: my_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  db_data:
  redis_data:
